# Generated by Django 4.1.3 on 2023-10-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221205_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordProtection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='profile_picture',
        ),
    ]
