# Generated by Django 4.1.3 on 2023-10-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_passwordprotection_remove_author_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordProtection',
        ),
    ]
